"""add document storage path

Revision ID: 151276388eee
Revises: d77c73fe1fe4
Create Date: 2026-08-23 16:46:18.462039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "151276388eee"
down_revision: Union[str, Sequence[str], None] = "d77c73fe1fe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "documents",
        sa.Column(
            "storage_path",
            sa.String(length=500),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE documents "
        "SET storage_path = 'legacy/unknown' "
        "WHERE storage_path IS NULL"
    )

    op.alter_column(
        "documents",
        "storage_path",
        existing_type=sa.String(length=500),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "storage_path")
    # ### end Alembic commands ###
