"""add unique constraint to tenant membership

Revision ID: 4350739915f4
Revises: 1574707e3088
Create Date: 2026-08-22 20:04:12.582840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4350739915f4'
down_revision: Union[str, Sequence[str], None] = '1574707e3088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenant_member_user_tenant', 'tenant_members', ['user_id', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_member_user_tenant', 'tenant_members', type_='unique')
    # ### end Alembic commands ###
